<a href="https://colab.research.google.com/github/Iddhie/Linear_Algebra/blob/main/Exercise8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Gauss-Jordan Elimination (1)
Algorithm Steps

1. Make the top-left entry (the pivot) equal to 1 by scaling the row.
2. Make all other entries in the pivot column zero by performing row operations.
3. Move to the next column and repeat steps 2-3 for each column.
4. Continue this process for each row and column until the matrix is in reduced row-echelon form.

In [20]:
import numpy as np

def gauss_jordan_elimination(matrix):
    matrix = np.array(matrix, dtype=float)
    rows, cols = matrix.shape
    for i in range(rows):
        pivot = matrix[i, i]
        if pivot == 0:
            pivot_row = i
            for j in range(i + 1, rows):
                if matrix[j, i] != 0:
                    pivot_row = j
                    break
            if pivot_row != i:
                matrix[i], matrix[pivot_row] = matrix[pivot_row].copy(), matrix[i].copy()
                pivot = matrix[i, i]
        if pivot == 0:
            continue
        matrix[i] = matrix[i] / pivot
        for j in range(rows):
            if j != i:
                matrix[j] -= matrix[j, i] * matrix[i]
    return matrix

matrix1 = [
    [4, 2, 1, 8],
    [2, 1, 3, 5],
    [1, 3, 2, 9]
]

matrix2 = [
    [3, 2, 1, 4],
    [1, 2, 1, 3],
    [2, 1, 2, 1]
]

rref_matrix1 = gauss_jordan_elimination(matrix1)
rref_matrix2 = gauss_jordan_elimination(matrix2)

print("Reduced Row Echelon Form of Matrix 1:")
for row in rref_matrix1:
    print(row)

print("Reduced Row Echelon Form of Matrix 2:")
for row in rref_matrix2:
    print(row)


Reduced Row Echelon Form of Matrix 1:
[1.   0.   0.   0.64]
[0.   1.   0.   2.52]
[0.  0.  1.  0.4]
Reduced Row Echelon Form of Matrix 2:
[1.  0.  0.  0.5]
[0.         1.         0.         1.66666667]
[ 0.          0.          1.         -0.83333333]


## Gauss-Jordan Elimination (2)
$$
\left[\begin{array}{ccc|c}
1 & 2 & 3 & 4 \\
2 & 3 & 4 & 5 \\
3 & 4 & 5 & 6
\end{array}\right]
$$

$R2=R2-2R1, R3=R3-3R1$

$$
\left[\begin{array}{ccc|c}
1 & 2 & 3 & 4 \\
0 & -1 & -2 & -3 \\
0 & -2 & -4 & -6
\end{array}\right]
$$

$R2=-R2$

$$
\left[\begin{array}{ccc|c}
1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 \\
0 & -2 & -4 & -6
\end{array}\right]
$$

$R1=R1-2R2, R3=R3+2R2$

$$
\left[\begin{array}{ccc|c}
1 & 0 & -1 & -2 \\
0 & 1 & 2 & 3 \\
0 & 0 & 0 & 0
\end{array}\right]
$$

## Gauss-Jordan Elimination (3)

$$
\left[\begin{array}{ccc|c}
3 & 2 & 1 & 4 \\
1 & 2 & 1 & 3 \\
2 & 1 & 2 & 2
\end{array}\right]
$$

$R1=R1/3$

$$
\left[\begin{array}{ccc|c}
1 & \frac{2}{3} & \frac{1}{3} & \frac{4}{3} \\
1 & 2 & 1 & 3 \\
2 & 1 & 2 & 2
\end{array}\right]
$$

$R2=R2-R1, R3=R3-2R1$

$$
\left[\begin{array}{ccc|c}
1 & \frac{2}{3} & \frac{1}{3} & \frac{4}{3} \\
0 & \frac{4}{3} & \frac{2}{3} & \frac{5}{3} \\
0 & \frac{-1}{3} & \frac{4}{3} & \frac{-2}{3}
\end{array}\right]
$$

$R2=3R2/4$

$$
\left[\begin{array}{ccc|c}
1 & \frac{2}{3} & \frac{1}{3} & \frac{4}{3} \\
0 & 1 & \frac{1}{2} & \frac{5}{4} \\
0 & \frac{-1}{3} & \frac{4}{3} & \frac{-2}{3}
\end{array}\right]
$$

$R1=R1-2R2/3, R3=R3/3,R3=2R3/3$

$$
\left[\begin{array}{ccc|c}
1 & 0 & 0 & \frac{1}{2} \\
0 & 1 & \frac{1}{2} & \frac{5}{4} \\
0 & 0 & 1 & \frac{-1}{6}
\end{array}\right]
$$

$R2=R2-R3/2$

$$
\left[\begin{array}{ccc|c}
1 & 0 & 0 & \frac{1}{2} \\
0 & 1 & 0 & \frac{4}{3} \\
0 & 0 & 1 & \frac{-1}{6}
\end{array}\right]
$$




## Gauss-Jordan Elimination (4)

$$
\left[\begin{array}{ccc|c}
4 & 2 & 1 & 8 \\
2 & 1 & 3 & 5 \\
1 & 3 & 2 & 9
\end{array}\right]
$$

$$
\left[\begin{array}{ccc|c}
1 & \frac{1}{2} & \frac{1}{4} & 2 \\
2 & 1 & 3 & 5 \\
1 & 3 & 2 & 9
\end{array}\right]
$$

$R2=R2-2R1,R3=R3-R1$

$$
\left[\begin{array}{ccc|c}
1 & \frac{1}{2} & \frac{1}{4} & 2 \\
0 & 0 & \frac{5}{2} & 1 \\
0 & \frac{5}{2} & \frac{7}{4} & 7
\end{array}\right]
$$

$Swap \space R2 \space and \space R3, R2=2R2/5$

$$
\left[\begin{array}{ccc|c}
1 & \frac{1}{2} & \frac{1}{4} & 2 \\
0 & 1 & \frac{7}{10} & \frac{14}{5} \\
0 & 0 & \frac{5}{2} & 1
\end{array}\right]
$$

$R1=R1-R2/2, R3=2R3/5$

$$
\left[\begin{array}{ccc|c}
1 & 0 & \frac{-1}{10} & \frac{3}{5} \\
0 & 1 & \frac{7}{10} & \frac{14}{5} \\
0 & 0 & 1 & \frac{2}{5}
\end{array}\right]
$$

$R1=R1+R3/10, R2=R2-7R3/10$
$$
\left[\begin{array}{ccc|c}
1 & 0 & 0 & \frac{16}{25} \\
0 & 1 & 0 & \frac{63}{25} \\
0 & 0 & 1 & \frac{2}{5}
\end{array}\right]
$$
